### ISSUE TITLE
Ship cannot be assembled if its y exceeds 254.

### ISSUE THREAD

**Issue by hoobooh** [ValkyrienSkies/Valkyrien-Skies#367]
Title

**Comment by Rubydesic** [comment]
crash log:

```
[22:05:33] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: 3:256:-30 is out of range from BlockPos{x=5120240, y=0, z=35056}
    at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
    at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
    at net.minecraft.util.Util.func_181617_a(Util.java:48) [h.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279) [chd.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```
