### ISSUE TITLE
world.class`s world variable was not compatible with Catserver`s world variable

### ISSUE THREAD

**Issue by SIZStan** [ValkyrienSkies/Valkyrien-Skies#371]
java.lang.NoSuchFieldError: world
        at net.minecraft.world.World.<init>(World.java:193) ~[amu.class:?]
        at net.minecraft.world.WorldServer.<init>(WorldServer.java:117) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:357) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:328) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:600) [MinecraftServer.class:?]

 When the developer of catserver tries to modify the variables, it gets worked, but this is only a temporary method that cannot be used all the time

**Comment by DeltaNedas** [comment]
only forge server is officially supported
please stop using weird servers

**Comment by SIZStan** [comment]
Haha. In fact, catserver is a forge + bukkit server, which is convenient for users to use and very popular.
https://github.com/Luohuayu/CatServer
It`s free and open source

**Comment by DeltaNedas** [comment]
well then it would work
forge is lgpl, it has to be foss, this is no surprise. so is vs code but its still shit
either way cat server is not official forge

**Comment by SIZStan** [comment]
ok, fine so....
Another issue...[https://github.com/ValkyrienSkies/Valkyrien-Skies/issues/372](https://github.com/ValkyrienSkies/Valkyrien-Skies/issues/372)

**Comment by Rubydesic** [comment]
also, fixed on latest master
