### ISSUE TITLE
Valkryien skies crashing server on startup

### ISSUE THREAD

**Issue by TheCrazyInsanity** [ValkyrienSkies/Valkyrien-Skies#374]
et.minecraft.server.MinecraftServer]: Encountered an unexpected exception
--
90 | java.lang.NoSuchFieldError: world
91 | at net.minecraft.world.World.<init>(World.java:170) ~[amu.class:?]
92 | at net.minecraft.world.WorldServer.<init>(WorldServer.java:114) ~[oo.class:?]
93 | at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:397) ~[MinecraftServer.class:?]
94 | at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:316) ~[nz.class:?]
95 | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:662) [MinecraftServer.class:?]
96 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by youngklps** [comment]
I got it too

(Exception in server tick loop)

java.lang.NoSuchFieldError: world
	at net.minecraft.world.World.<init>(World.java:181)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:139)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:353)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:319)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587)
	at java.lang.Thread.run(Unknown Source)

**Comment by DeltaNedas** [comment]
need more info like:
- full latest.log
- version and build number from circleci/jenkins
- jre and jvm
- server
ill try to replicate on latest breaking/1.0

**Comment by youngklps** [comment]
The mod version is the latest released one on bukkit...And the full latest.log is missing...Sorry
Java Version: 1.8.0_181
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode)
The server is catserver,which is compatible with bukkit plugins and mods.
I'm uploading the server core now...plz wait

**Comment by youngklps** [comment]
The server core could be downloaded in https://github.com/Luohuayu/CatServer
Probably that's not because the server core...when I use vanilla+forge with VS , it also crashes

**Comment by youngklps** [comment]
Well,after using the latest dev build, the crash disappeared.
But the consle kept spamming
[22:06:11] [Server thread/WARN] []: java.lang.Exception: Tried getting entities from giant bounding box of box[-37.08949688856244, 40.0, -108.83239468055487 -> 12.910503111437567, 90.0, -58.83239468055487]
[22:06:11] [Server thread/WARN] []: 	at net.minecraft.world.World.func_175674_a(World.java:4740)
[22:06:11] [Server thread/WARN] []: 	at cn.lambdalib2.util.WorldUtils.getEntities(WorldUtils.java:205)
[22:06:11] [Server thread/WARN] []: 	at cn.lambdalib2.util.WorldUtils.getEntities(WorldUtils.java:200)
[22:06:11] [Server thread/WARN] []: 	at cn.lambdalib2.util.WorldUtils.getEntities(WorldUtils.java:192)
[22:06:11] [Server thread/WARN] []: 	at cn.academy.ability.context.ContextManager$ServerManager.hBeginLink(ContextManager.java:414)
[22:06:11] [Server thread/WARN] []: 	at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
[22:06:11] [Server thread/WARN] []: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[22:06:11] [Server thread/WARN] []: 	at java.lang.reflect.Method.invoke(Unknown Source)
[22:06:11] [Server thread/WARN] []: 	at cn.lambdalib2.s11n.network.NetworkMessage$2.invoke(NetworkMessage.java:230)
[22:06:11] [Server thread/WARN] []: 	at cn.lambdalib2.s11n.network.NetworkMessage.invokeListener(NetworkMessage.java:157)
[22:06:11] [Server thread/WARN] []: 	at cn.lambdalib2.s11n.network.NetworkMessage.processMessage(NetworkMessage.java:138)
[22:06:11] [Server thread/WARN] []: 	at cn.lambdalib2.s11n.network.NetworkMessage.access$000(NetworkMessage.java:54)
[22:06:11] [Server thread/WARN] []: 	at cn.lambdalib2.s11n.network.NetworkMessage$Handler.lambda$onMessage$0(NetworkMessage.java:381)
[22:06:11] [Server thread/WARN] []: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[22:06:11] [Server thread/WARN] []: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[22:06:11] [Server thread/WARN] []: 	at net.minecraft.util.Util.func_181617_a(Util.java:50)
[22:06:11] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846)
[22:06:11] [Server thread/WARN] []: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:473)
[22:06:11] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783)
[22:06:11] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
[22:06:11] [Server thread/WARN] []: 	at java.lang.Thread.run(Unknown Source)

**Comment by youngklps** [comment]
Ummmmm,creating the boat in server crashes the server
Using the latest dev build

Description: Ticking block entity

java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
	at org.valkyrienskies.mod.common.multithreaded.VSExecutors.<clinit>(VSExecutors.java:14)
	at org.valkyrienskies.mod.common.util.ValkyrienUtils.assembleShipAsOrderedByPlayer(ValkyrienUtils.java:244)
	at org.valkyrienskies.mod.common.tileentity.TileEntityPhysicsInfuser.func_73660_a(TileEntityPhysicsInfuser.java:112)
	at net.minecraft.world.World.func_72939_s(World.java:2168)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:742)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:913)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:473)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiScreen
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 10 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@64652cf6 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 12 more
Caused by: java.lang.RuntimeException: Attempted to load class blk for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	... 14 more

**Comment by Rubydesic** [comment]
The latest version of master should be compatible with all of these bukkit/forge hybrids like catserver and muhist.
