### ISSUE TITLE
NullPointerException in WorldServerShipManager on dimension unload

### ISSUE THREAD

**Issue by AutonomicPerfectionist** [ValkyrienSkies/Valkyrien-Skies#385]
Began happenening after adding RandomThings, OreExcavation, and WarpDrive to my server (VS has been there for awhile without issue), unsure which is causing the bug but will make a test server soon to figure out which. Crash occurs rarely when a player returns from a dimension (so far only Arroma1997's Dimensional World, testing the End and the Nether currently) to the Overworld (on dimension unload). Warpdrive does some things with world borders but other than that there's not much I can think of that could be directly messing with unload. Forge priority shows only VS at highest priority for the dimension unload event, High shows XReliquary, Normal shows a whole crapton of mods that I will try to trim down as soon as possible. We have 8 ships in the overworld but none of them are currently assembled. No ships in any other dimension. Server was up for two days before the first crash, second crash occured after three hours, both errors occured upon unloading dimension with ID -6 (Aroma's) both times, stack trace exactly the same. Let me know what other information you require, I can get you a full mods list but there's 283 of them so I doubt that will be much help. I will try to bring up a minimal server that exhibits the bug as soon as possible.

Version:1.12.2-1.0-alpha-1

Stacktrace:
[22:31:36] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.WorldEvent$Unload@14219f91:
java.lang.NullPointerException: null
        at org.valkyrienskies.mod.common.ship_handling.WorldServerShipManager.onWorldUnload(WorldServerShipManager.java:28) ~[WorldServerShipManager.class:?]
        at org.valkyrienskies.mod.common.EventsCommon.onWorldUnload(EventsCommon.java:224) ~[EventsCommon.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2103_EventsCommon_onWorldUnload_Unload.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at com.unnoen.unloader.UnloadHandler.tick(UnloadHandler.java:48) [UnloadHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2093_UnloadHandler_tick_ServerTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:712) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]

**Comment by AutonomicPerfectionist** [comment]
It appears WarpDrive has a config option for enforcing a minimum delay on dimensionUnload, in warpdrive/config.yml: I:minimum_dimension_unload_queue_delay_ticks=100 is the default. Possible this is the culprit.

**Comment by LemADEC** [comment]
100 is the minimum to prevent world/dimension transition issues (namely, unloading the dimension while transfer/load is ongoing).

**Comment by Rubydesic** [comment]
I would suggest that Aroma's dimension is the issue, it is probably getting unloaded TWICE somehow. At any rate, I don't think this issue will resurface with the latest version. I am closing the issue. Please reopen if any questions
