### ISSUE TITLE
Crash when using OpenJDK8U openj9 build 1.8.0_265-b01

### ISSUE THREAD

**Issue by E-daw** [ValkyrienSkies/Valkyrien-Skies#421]
Hello,

On my server and client I'm experiencing a crash when using this mod with Openjdk8u.

java.lang.ExceptionInInitializerError: null
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:147) ~[?:1.8.0_265]
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:136) ~[?:1.8.0_265]
	at org.valkyrienskies.mod.common.ships.QueryableShipData.<init>(QueryableShipData.java:71) ~[QueryableShipData.class:?]
	at org.valkyrienskies.mod.common.ships.QueryableShipData.<init>(QueryableShipData.java:43) ~[QueryableShipData.class:?]
	at org.valkyrienskies.mod.common.ships.ship_world.VSWorldData.<init>(VSWorldData.java:10) ~[VSWorldData.class:?]
	at org.valkyrienskies.mod.common.capability.VSWorldDataCapability$$Lambda$2140/0000000000000000.get(Unknown Source) ~[?:?]
	at org.valkyrienskies.mod.common.capability.framework.VSDefaultCapability.<init>(VSDefaultCapability.java:57) ~[VSDefaultCapability.class:?]
	at org.valkyrienskies.mod.common.capability.framework.VSDefaultCapability.<init>(VSDefaultCapability.java:51) ~[VSDefaultCapability.class:?]
	at org.valkyrienskies.mod.common.capability.VSWorldDataCapability.<init>(VSWorldDataCapability.java:17) ~[VSWorldDataCapability.class:?]
	at org.valkyrienskies.mod.common.capability.VSCapabilityRegistry$$Lambda$1199/0000000000000000.call(Unknown Source) ~[?:?]
	at net.minecraftforge.common.capabilities.Capability.getDefaultInstance(Capability.java:129) ~[Capability.class:?]
	at org.valkyrienskies.mod.common.capability.framework.VSDefaultCapabilityProvider.<init>(VSDefaultCapabilityProvider.java:18) ~[VSDefaultCapabilityProvider.class:?]
	at org.valkyrienskies.mod.common.capability.VSCapabilityRegistry.attachWorldCapabilities(VSCapabilityRegistry.java:33) ~[VSCapabilityRegistry.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_585_VSCapabilityRegistry_attachWorldCapabilities_AttachCapabilitiesEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:691) ~[ForgeEventFactory.class:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:679) ~[ForgeEventFactory.class:?]
	at net.minecraft.world.World.initCapabilities(World.java:3978) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:173) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:823) [?:1.8.0_265]
Caused by: java.lang.IllegalStateException: Could not resolve sufficient generic type information from the given function of type: org.valkyrienskies.mod.common.ships.ShipData$$Lambda$2142/0000000000000000, resolved: [class net.jodah.typetools.TypeResolver$Unknown, class net.jodah.typetools.TypeResolver$Unknown]. If the function you supplied was created from a lambda expression, then it's likely that the host JVM does not allow the generic type information to be read from lambda expressions. Alternatively, if you supplied a class-based implementation of the function, then you must ensure that you specified the generic types of the function when it was compiled. As a workaround, you can use the counterpart methods in QueryFactory which allow the generic types to be specified explicitly.
	at com.googlecode.cqengine.query.QueryFactory.validateSimpleFunctionGenericTypes(QueryFactory.java:1084) ~[QueryFactory.class:?]
	at com.googlecode.cqengine.query.QueryFactory.resolveSimpleFunctionGenericTypes(QueryFactory.java:1070) ~[QueryFactory.class:?]
	at com.googlecode.cqengine.query.QueryFactory.nullableAttribute(QueryFactory.java:909) ~[QueryFactory.class:?]
	at com.googlecode.cqengine.query.QueryFactory.nullableAttribute(QueryFactory.java:888) ~[QueryFactory.class:?]
	at org.valkyrienskies.mod.common.ships.ShipData.<clinit>(ShipData.java:146) ~[ShipData.class:?]
	... 22 more

**Comment by Rubydesic** [comment]
we don't support openj9, use hotspot

**Comment by gatoborrachon** [comment]
@E-daw this issue was fixed by OpenJ9 side, you can get the latest release here:
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2020-12-10-04-05/OpenJDK8U-jdk_x64_windows_openj9_2020-12-10-04-05.zip
