### ISSUE TITLE
Crash to launcher exit code -1, Caught exception from Forestry (forestry)

### ISSUE THREAD

**Issue by Nogorth87** [ValkyrienSkies/Valkyrien-Skies#436]
Game crashes shortly after launching minecraft, (1.12.2)
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Forestry (forestry)
Exit Code: -1

**Comment by Sunspot0411** [comment]
This should be mod conflict, please send the crash report or log

**Comment by Nogorth87** [comment]
hello, here's the crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  CTMCorePlugin (Connected-Textures-Mod-1.12.2.jar)
  MixinLoaderForge (valkyrien-skies-1.12.2-1.1.0.jar)
  ForgelinPlugin (Shadowfacts-Forgelin-1.12.2.jar)
  MovingWorldCore (MovingWorld-Mod-1.12.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 11/30/20 12:23 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Forestry (forestry)
Caused by: java.lang.ExceptionInInitializerError
	at forestry.core.blocks.BlockRegistryCore.<init>(BlockRegistryCore.java:36)
	at forestry.core.ModuleCore.registerItemsAndBlocks(ModuleCore.java:133)
	at forestry.modules.InternalModuleHandler.runSetup(InternalModuleHandler.java:84)
	at forestry.Forestry.preInit(Forestry.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at org.valkyrienskies.mod.common.capability.framework.VSDefaultCapabilityProviderTransient.<init>(VSDefaultCapabilityProviderTransient.java:17)
	at org.valkyrienskies.mod.common.capability.VSCapabilityRegistry.attachEntityCapabilities(VSCapabilityRegistry.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_157_VSCapabilityRegistry_attachEntityCapabilities_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:691)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:661)
	at net.minecraft.entity.Entity.<init>(Entity.java:219)
	at net.minecraft.entity.item.EntityItem.<init>(EntityItem.java:73)
	at forestry.core.render.RenderAnalyzer.<init>(RenderAnalyzer.java:32)
	at forestry.core.proxy.ProxyRenderClient.setRendererAnalyzer(ProxyRenderClient.java:82)
	at forestry.core.blocks.BlockTypeCoreTesr.createAnalyzerProperties(BlockTypeCoreTesr.java:28)
	at forestry.core.blocks.BlockTypeCoreTesr.<clinit>(BlockTypeCoreTesr.java:19)
	... 44 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 734603832 bytes (700 MB) / 1610612736 bytes (1536 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_E3 61 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version                 | Source                                          | Signature                                |
	|:----- |:-------------------------------------------- |:----------------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                                    | 1.12.2                  | minecraft.jar                                   | None                                     |
	| LCH   | mcp                                          | 9.42                    | minecraft.jar                                   | None                                     |
	| LCH   | FML                                          | 8.0.99.99               | forge-1.12.2-14.23.5.2854.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                                        | 14.23.5.2854            | forge-1.12.2-14.23.5.2854.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | micdoodlecore                                |                         | minecraft.jar                                   | None                                     |
	| LCH   | com.elytradev.movingworld.common.asm.coremod |                         | minecraft.jar                                   | None                                     |
	| LCH   | dsurroundcore                                | 3.5.4.3                 | minecraft.jar                                   | None                                     |
	| LCH   | jei                                          | 4.15.0.287              | jei_1.12.2-4.15.0.287.jar                       | None                                     |
	| LCH   | appleskin                                    | 1.0.9                   | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| LCH   | biomesoplenty                                | 7.0.1.2427              | BiomesOPlenty-1.12.2-7.0.1.2427-universal.jar   | None                                     |
	| LCH   | buildcraftlib                                | 7.99.24.1               | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| LCH   | buildcraftcore                               | 7.99.24.1               | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| LCH   | buildcraftbuilders                           | 7.99.24.1               | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| LCH   | buildcrafttransport                          | 7.99.24.1               | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| LCH   | buildcraftsilicon                            | 7.99.24.1               | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| LCH   | buildcraftenergy                             | 7.99.24.1               | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| LCH   | ic2                                          | 2.8.100-ex112           | Industrial-Craft-2-Mod-Experimental-1.12.2.jar  | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCE   | forestry                                     | 5.8.0.311               | Forestry-Mod-1.12.2.jar                         | None                                     |
	| LC    | buildcraftcompat                             | 7.99.24.1               | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| LC    | buildcraftfactory                            | 7.99.24.1               | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| LC    | buildcraftrobotics                           | 7.99.24.1               | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| LC    | ctm                                          | MC1.12.2-0.3.3.22       | Connected-Textures-Mod-1.12.2.jar               | None                                     |
	| LC    | chisel                                       | MC1.12.2-0.2.0.31       | Chisel-Mod-1.12.2.jar                           | None                                     |
	| LC    | chiselsandbits                               | 14.33                   | chiselsandbits-14.33.jar                        | None                                     |
	| LC    | codechickenlib                               | 3.2.3.358               | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux                                 | 2.1.1                   | RedstoneFlux-1.12-2.1.1.1-universal.jar         | None                                     |
	| LC    | cofhcore                                     | 4.6.6                   | CoFHCore-1.12.2-4.6.6.1-universal.jar           | None                                     |
	| LC    | cofhworld                                    | 1.3.0                   | CoFHWorld-1.12.2.jar                            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | compactmachines3                             | 3.0.18                  | Compact-Machines-Mod-1.12.2.jar                 | None                                     |
	| LC    | cookingforblockheads                         | 6.4.71                  | CookingForBlockheads_1.12.2-6.4.71.jar          | None                                     |
	| LC    | customnpcs                                   | 1.12                    | CustomNPCs_1.12.2-(05Jul20).jar                 | None                                     |
	| LC    | movingworld                                  | 1.12-6.342              | MovingWorld-Mod-1.12.jar                        | None                                     |
	| LC    | davincisvessels                              | @DVESSELSVER@           | Davincis-Vessels-Mod-1.12.2.jar                 | None                                     |
	| LC    | equipmenttooltips                            | 1.0.3                   | EquipmentTooltips-1.12.2-1.0.3-4.jar            | None                                     |
	| LC    | mantle                                       | 1.12-1.3.3.55           | Mantle-Mod-1.12.2.jar                           | None                                     |
	| LC    | tconstruct                                   | 1.12.2-2.12.0.115       | Tinkers-Construct-Mod-1.12.2.jar                | None                                     |
	| LC    | extrautils2                                  | 1.0                     | extrautils2-1.12-1.9.9.jar                      | None                                     |
	| LC    | zerocore                                     | 1.12.2-0.1.2.8          | zerocore-1.12.2-0.1.2.8.jar                     | None                                     |
	| LC    | bigreactors                                  | 1.12.2-0.4.5.65         | ExtremeReactors-1.12.2-0.4.5.65.jar             | None                                     |
	| LC    | galacticraftcore                             | 4.0.1.181               | Galacticraft-Mod-1.12.2.jar                     | None                                     |
	| LC    | gravestone                                   | 1.10.2                  | gravestone-1.10.2.jar                           | None                                     |
	| LC    | waila                                        | 1.8.26                  | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| LC    | icbmclassic                                  | 1.12.2-4.0.1.75         | ICBM-classic-1.12.2-4.0.1b75.jar                | None                                     |
	| LC    | journeymap                                   | 1.12.2-5.5.5b7          | JourneyMap-Mod-1.12.2-Unlimited.jar             | None                                     |
	| LC    | libvulpes                                    | 0.4.0.-57               | LibVulpes-1.12.2.jar                            | None                                     |
	| LC    | metallurgy                                   | 1.1.2                   | Metallurgy-4-Reforged-1.1.2.jar                 | None                                     |
	| LC    | recipehandler                                | 0.13                    | NoMoreRecipeConflict-0.13(1.12.2).jar           | None                                     |
	| LC    | harvestcraft                                 | 1.12.2zb                | Pam's+HarvestCraft+1.12.2zg.jar                 | None                                     |
	| LC    | railcraft                                    | 12.0.0                  | railcraft-12.0.0.jar                            | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LC    | reforged                                     | 0.7.5                   | Reforged-0.7.5-1.12+.jar                        | None                                     |
	| LC    | rustic                                       | 0.4.8                   | Rustic-Mod-1.12.2.jar                           | None                                     |
	| LC    | forgelin                                     | 1.8.2                   | Shadowfacts-Forgelin-1.12.2.jar                 | None                                     |
	| LC    | thermalfoundation                            | 2.6.7                   | ThermalFoundation-1.12.2-2.6.7.1-universal.jar  | None                                     |
	| LC    | thermalexpansion                             | 5.5.7                   | ThermalExpansion-1.12.2-5.5.7.1-universal.jar   | None                                     |
	| LC    | treechopper                                  | 1.2.4                   | TreeChopper-1.12.2-1.2.4.jar                    | None                                     |
	| LC    | valkyrienskies                               | 1.12.2-1.1.0            | valkyrien-skies-1.12.2-1.1.0.jar                | None                                     |
	| LC    | orelib                                       | 3.5.2.2                 | OreLib-1.12.2-3.5.2.2.jar                       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LC    | dsurround                                    | 3.5.4.3                 | DynamicSurroundings-1.12.2-3.5.4.3.jar          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LC    | immersiveengineering                         | 0.12-89                 | Immersive-Engineering-Mod-1.12.2.jar            | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LC    | structurize                                  | 1.12.2-0.10.277-RELEASE | structurize-1.12.2-0.10.277-RELEASE.jar         | None                                     |
	| LC    | minecolonies                                 | 1.12.2-0.11.811-BETA    | minecolonies-1.12.2-0.11.811-BETA-universal.jar | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CTMCorePlugin (Connected-Textures-Mod-1.12.2.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MixinLoaderForge (valkyrien-skies-1.12.2-1.1.0.jar)
  
ForgelinPlugin (Shadowfacts-Forgelin-1.12.2.jar)
  
MovingWorldCore (MovingWorld-Mod-1.12.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GTX 1050/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

**Comment by Sunspot0411** [comment]
VS is incompatible with Forestry mod, you have to remove Forestry to run VS

**Comment by Nogorth87** [comment]
Oh well, that's a shame, i'll make a separate modpack for vs then, i guess.
Thanks for responding and for looking into this though!
