### ISSUE TITLE
Littletiles incompatibility

### ISSUE THREAD

**Issue by Ilya-torshov** [ValkyrienSkies/Valkyrien-Skies#487]
Incompatibility with LittleTiles, causes LT structures to not render. Happens even when the LT structure is not on a ship, and when no ship exists or has been assembled in a world.

**Comment by Zatzou** [comment]
I'm also having this same issue. It's spamming the logs with the following entry which is also causing the logs to be gigabytes in size.

```
[01:06:56] [Thread-62/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5208]: Something just went wrong here, getting default light value instead!
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]: org.valkyrienskies.mod.common.util.multithreaded.CalledFromWrongThreadException: Wrong thread calling code: Thread[Thread-61,5,main]
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at org.valkyrienskies.mod.common.ships.ship_world.WorldClientShipManager.enforceGameThread(WorldClientShipManager.java:38)
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at org.valkyrienskies.mod.common.ships.ship_world.WorldClientShipManager.getPhysObjectsInAABB(WorldClientShipManager.java:113)
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraft.world.World.handler$zch000$preGetCombinedLight(World.java:5161)
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraft.world.World.func_175626_b(World.java)
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraft.block.Block.func_185484_c(Block.java:378)
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185889_a(BlockStateContainer.java:362)
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraftforge.client.model.pipeline.BlockInfo.updateLightMatrix(BlockInfo.java:127)
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraftforge.client.model.pipeline.VertexLighterSmoothAo.updateBlockInfo(VertexLighterSmoothAo.java:183)
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at com.creativemd.creativecore.client.rendering.model.CreativeModelPipeline.renderBlockFaceSmooth(CreativeModelPipeline.java:132)
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at com.creativemd.littletiles.client.render.cache.RenderingThread.run(RenderingThread.java:293)
```

for me the lt structures do eventually render but it takes a long time.
