### ISSUE TITLE
it keeps crashing idk why heres the report

### ISSUE THREAD

**Issue by EnderBoi201** [ValkyrienSkies/Valkyrien-Skies#518]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MixinLoaderForge ([[valkyrien-skies-1.1.7-all]].jar)
  ObfuscatePlugin (obfuscate-0.2.7-1.12.2.jar)
  McLib core mod (mclib-2.3.7-1.12.2.jar)
  SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.jar)
  BlockbusterCore (blockbuster-2.4.1-1.12.2 (1).jar)
  FutureMC (future-mc-0.2.8.jar)
  ShutdownPatcher (mcef-1.12.2-1.11b-coremod.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 2/22/22 4:41 PM
Description: Starting integrated server

java.lang.NoClassDefFoundError: net/minecraft/server/management/PlayerList
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2369)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:224)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:416)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.management.PlayerList
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:373)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:227)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:195)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 18 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [securitycraft.mixins.json:camera.MixinPlayerList] from phase [DEFAULT] in config [securitycraft.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:646)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:598)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:366)
	... 23 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("FIELD") on net/minecraft/server/management/PlayerList::broadcastToCameras with priority 1000 cannot inject into net/minecraft/server/management/PlayerList::func_148543_a(Lnet/minecraft/entity/player/EntityPlayer;DDDDILnet/minecraft/network/Packet;)V merged by org.valkyrienskies.mixin.server.management.MixinPlayerList with priority 1000 [PREINJECT Applicator Phase -> securitycraft.mixins.json:camera.MixinPlayerList -> Prepare Injections ->  -> handler$zzc000$broadcastToCameras(Lnet/minecraft/entity/player/EntityPlayer;DDDDILnet/minecraft/network/Packet;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;ILnet/minecraft/entity/player/EntityPlayerMP;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1315)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1064)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:391)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:321)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:573)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:361)
	... 23 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2369)

-- Starting integrated server --
Details:
	Level ID: New World------------------------------------------------------------
	Level Name: New World
Stacktrace:
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2369)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:224)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:416)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiMainMenu
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 518762560 bytes (494 MB) / 1342177280 bytes (1280 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 32 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID               | Version                    | Source                                         | Signature                                |
	|:------ |:---------------- |:-------------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft        | 1.12.2                     | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp              | 9.42                       | minecraft.jar                                  | None                                     |
	| LCHIJA | FML              | 8.0.99.99                  | forge-1.12.2-14.23.5.2855.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge            | 14.23.5.2855               | forge-1.12.2-14.23.5.2855.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | cubicchunkscore  | 1.12.2-0.0.1208.0-SNAPSHOT | minecraft.jar                                  | None                                     |
	| LCHIJA | obfuscate        | 0.2.7                      | minecraft.jar                                  | None                                     |
	| LCHIJA | securitycraft    | v1.9                       | [1.12.2]+SecurityCraft+v1.9.jar                | None                                     |
	| LCHIJA | valkyrienskies   | 1.1.7                      | [[valkyrien-skies-1.1.7-all]].jar              | None                                     |
	| LCHIJA | mclib            | 2.3.7                      | mclib-2.3.7-1.12.2.jar                         | None                                     |
	| LCHIJA | metamorph        | 1.2.13                     | metamorph-1.2.13-1.12.2.jar                    | None                                     |
	| LCHIJA | blockbuster      | 2.4.1                      | blockbuster-2.4.1-1.12.2 (1).jar               | None                                     |
	| LCHIJA | cdm              | 0.4.1                      | cdm-0.4.1-mc1.12.2.jar                         | None                                     |
	| LCHIJA | cubicchunks      | 1.12.2-0.0.1208.0-SNAPSHOT | CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar | None                                     |
	| LCHIJA | doge             | 0.6.0                      | DogeMod-1.12.2-0.6.0.jar                       | None                                     |
	| LCHIJA | flansmod         | 5.10.0                     | Flan's+Mod-1.12.2-5.10.0 (1).jar               | None                                     |
	| LCHIJA | forgelin         | 1.8.4                      | Forgelin-1.8.4.jar                             | None                                     |
	| LCHIJA | futuremc         | 0.2.6                      | future-mc-0.2.8.jar                            | None                                     |
	| LCHIJA | gitwebbuilder    | 1.1                        | GitWeb+Builder-1.1.jar                         | None                                     |
	| LCHIJA | cgm              | 0.15.3                     | guns-0.15.3-1.12.2.jar                         | None                                     |
	| LCHIJA | mcef             | 1.11                       | mcef-1.12.2-1.11b.jar                          | None                                     |
	| LCHIJA | mechapartspack   | 5.7.2                      | Mecha+Parts-Content+Pack-1.12.2-5.7.2.jar      | None                                     |
	| LCHIJA | simplepartspack  | 5.7.2                      | Simple+Parts-Content+Pack-1.12.2-5.7.2.jar     | None                                     |
	| LCHIJA | toughasnails     | 3.1.0.141                  | ToughAsNails-1.12.2-3.1.0.141-universal.jar    | None                                     |
	| LCHIJA | slurp            | 0.3                        | slurp-1.12-0.3.jar                             | None                                     |
	| LCHIJA | titanpack        | 5.7.2                      | Titan-Content+Pack-1.12.2-5.7.2.jar            | None                                     |
	| LCHIJA | vehicle          | 0.43.0                     | vehicle-mod-0.43.0-1.12.2.jar                  | None                                     |
	| LCHIJA | vs_world         | 1.12.2-1.0.0               | vs-world-1.12.2-1.0.0.jar                      | None                                     |
	| LCHIJA | vs_control       | 1.12.2-1.1.1               | vs-control-1.12.2-1.1.1.jar                    | None                                     |
	| LCHIJA | webdisplays      | 1.1                        | webdisplays-1.12.2-1.1.jar                     | None                                     |
	| LCHIJA | ww2pack          | 5.7.2                      | WW2-Content+Pack-1.12.2-5.7.2 (1).jar          | None                                     |
	| UD     | blockbuster_core | 2.4.1                      | minecraft.jar                                  | None                                     |
	| UD     | mclib_core       | 2.3.7                      | minecraft.jar                                  | None                                     |

	Loaded coremods (and transformers): 
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.core.asm.transformer.CubicChunksWorldEditTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MixinLoaderForge ([[valkyrien-skies-1.1.7-all]].jar)
  
ObfuscatePlugin (obfuscate-0.2.7-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
McLib core mod (mclib-2.3.7-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.jar)
  
BlockbusterCore (blockbuster-2.4.1-1.12.2 (1).jar)
  mchorse.blockbuster.core.BBCoreClassTransformer
FutureMC (future-mc-0.2.8.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
ShutdownPatcher (mcef-1.12.2-1.11b-coremod.jar)
  net.montoyo.mcef.coremod.ShutdownPatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 511.65' Renderer: 'NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2'
	CubicChunks WorldGen Hang Watchdog samples: (no data)
	Launched Version: 1.12.2-forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 511.65, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Corn-carrot.zip, CornPlantbottom-double_plant_paeonia_bottom.zip, CornPlantTop-double_plant_paeonia_top.zip, windowsphone-brick.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz

**Comment by EnderBoi201** [comment]
pls help

**Comment by EnderBoi201** [comment]
[crash-2022-02-22_16.41.59-client.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies/files/8120421/crash-2022-02-22_16.41.59-client.txt)
