### ISSUE TITLE
Server doesn't even load, It's the only mod i have. 

### ISSUE THREAD

**Issue by GranSacoWea2** [ValkyrienSkies/Valkyrien-Skies#520]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoaderForge ([[[valkyrien-skies-1.1.7-all]].jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 4/27/22 9:40 AM
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:147)
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:136)
	at org.valkyrienskies.mod.common.ships.QueryableShipData.<init>(QueryableShipData.java:71)
	at org.valkyrienskies.mod.common.ships.QueryableShipData.<init>(QueryableShipData.java:43)
	at org.valkyrienskies.mod.common.ships.ship_world.VSWorldData.<init>(VSWorldData.java:10)
	at org.valkyrienskies.mod.common.capability.VSWorldDataCapability$$Lambda$324/0x00000000184b5f80.get(Unknown Source)
	at org.valkyrienskies.mod.common.capability.framework.VSDefaultCapability.<init>(VSDefaultCapability.java:57)
	at org.valkyrienskies.mod.common.capability.framework.VSDefaultCapability.<init>(VSDefaultCapability.java:51)
	at org.valkyrienskies.mod.common.capability.VSWorldDataCapability.<init>(VSWorldDataCapability.java:17)
	at org.valkyrienskies.mod.common.capability.VSCapabilityRegistry$$Lambda$252/0x0000000018307840.call(Unknown Source)
	at net.minecraftforge.common.capabilities.Capability.getDefaultInstance(Capability.java:129)
	at org.valkyrienskies.mod.common.capability.framework.VSDefaultCapabilityProvider.<init>(VSDefaultCapabilityProvider.java:18)
	at org.valkyrienskies.mod.common.capability.VSCapabilityRegistry.attachWorldCapabilities(VSCapabilityRegistry.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_9_VSCapabilityRegistry_attachWorldCapabilities_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:691)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:679)
	at net.minecraft.world.World.initCapabilities(World.java:3978)
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:173)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:823)
Caused by: java.lang.IllegalStateException: Could not resolve sufficient generic type information from the given function of type: org.valkyrienskies.mod.common.ships.ShipData$$Lambda$326/0x0000000018628120, resolved: [class net.jodah.typetools.TypeResolver$Unknown, class net.jodah.typetools.TypeResolver$Unknown]. If the function you supplied was created from a lambda expression, then it's likely that the host JVM does not allow the generic type information to be read from lambda expressions. Alternatively, if you supplied a class-based implementation of the function, then you must ensure that you specified the generic types of the function when it was compiled. As a workaround, you can use the counterpart methods in QueryFactory which allow the generic types to be specified explicitly.
	at com.googlecode.cqengine.query.QueryFactory.validateSimpleFunctionGenericTypes(QueryFactory.java:1084)
	at com.googlecode.cqengine.query.QueryFactory.resolveSimpleFunctionGenericTypes(QueryFactory.java:1070)
	at com.googlecode.cqengine.query.QueryFactory.nullableAttribute(QueryFactory.java:909)
	at com.googlecode.cqengine.query.QueryFactory.nullableAttribute(QueryFactory.java:888)
	at org.valkyrienskies.mod.common.ships.ShipData.<clinit>(ShipData.java:146)
	... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.0-159-generic
	Java Version: 1.8.0_272, Eclipse OpenJ9
	Java VM Version: Eclipse OpenJ9 VM (JRE 1.8.0 Linux amd64-64-Bit Compressed References 20201022_822 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - 41f03341d5 based on jdk8u272-b10), Eclipse OpenJ9
	Memory: 764529848 bytes (729 MB) / 1098383360 bytes (1047 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 9 total; -Xoptionsfile=/pro/bin/java/java8-openj9/lib/amd64/compressedrefs/options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2 -Xms1024M -Xmx5120M -XX:-UsePerfData
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID             | Version      | Source                             | Signature                                |
	|:------ |:-------------- |:------------ |:---------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft      | 1.12.2       | minecraft.jar                      | None                                     |
	| LCHIJA | mcp            | 9.42         | minecraft.jar                      | None                                     |
	| LCHIJA | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge          | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | valkyrienskies | 1.1.7        | [[[valkyrien-skies-1.1.7-all]].jar | None                                     |
	| LCHIJA | vs_world       | 1.12.2-1.0.0 | vs-world-1.12.2-1.0.0.jar          | None                                     |
	| LCHIJA | vs_control     | 1.12.2-1.1.1 | vs-control-1.12.2-1.1.1.jar        | None                                     |

	Loaded coremods (and transformers): 
MixinLoaderForge ([[[valkyrien-skies-1.1.7-all]].jar)
  
	Profiler Position: N/A (disabled)
	Player Count: 0 / 100; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by mewj** [comment]
remove the 2 brackets at the end of the filename, only put the 3 brackets at the front.

**Comment by Rubydesic** [comment]
Use hotspot vm
